### ISSUE TITLE
question about STDC2-Seg75

### ISSUE THREAD

**Issue by ydhongHIT** [RolandGao/RegSeg#10]
Hi, I note that you benchmark the computation of STDC2-Seg75 which is not reported in the CVPR2021 paper. Did you test the speed of STDC-Seg on your own platform? How about the results?

**Comment by RolandGao** [comment]
Hi, I did test the speed of STDC-Seg.

stdc1 768x1536
0.0202ms
stdc2 768x1536
0.0236ms

**Comment by ydhongHIT** [comment]
> Hi, I did test the speed of STDC-Seg.
> 
> stdc1 768x1536 0.0202ms stdc2 768x1536 0.0236ms

Thanks for your reply. So the fps is 49.5 and 42.4? I got 80.0 fps and 63.6 fps with the 2080Ti, slower than the results in the paper. Maybe the use of tensorrt is one reason.
